CREATE TABLE CLIENTE (
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(100) NOT NULL,
    CPF VARCHAR(11)
);

CREATE TABLE PRODUTO (
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    DESCRICAO VARCHAR(100) NOT NULL,
    PRECO_UNITARIO NUMERIC(20,2) NOT NULL DEFAULT 0
);

CREATE TABLE PEDIDO (
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    CLIENTE_ID INTEGER NOT NULL REFERENCES CLIENTE(ID),
    DATA_PEDIDO TIMESTAMP NOT NULL DEFAULT NOW(),
    STATUS VARCHAR(20)
    TOTAL NUMERIC(20,2) NOT NULL
);

CREATE TABLE ITEM_PEDIDO (
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    PEDIDO_ID INTEGER NOT NULL REFERENCES PEDIDO(ID),
    PRODUTO_ID INTEGER NOT NULL REFERENCES PRODUTO(ID),
    QUANTIDADE INTEGER NOT NULL DEFAULT 1
);

CREATE TABLE USUARIO (
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    LOGIN VARCHAR(100) NOT NULL,
    SENHA VARCHAR NOT NULL,
    ADMIN BOOLEAN NOT NULL DEFAULT FALSE
);